###############################################################################
# Created by write_sdc
###############################################################################
current_design sar_logic_diff
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 40.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.5000 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {comp_out}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {start}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {busy}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cmp_clk}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cmp_rst}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[4]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[5]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[6]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[7]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[8]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_n[9]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[4]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[5]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[6]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[7]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[8]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dac_p[9]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[4]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[5]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[6]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[7]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[8]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout[9]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dout_valid}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {eoc}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {samp_bot}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {samp_top}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0500 [get_ports {busy}]
set_load -pin_load 0.0500 [get_ports {cmp_clk}]
set_load -pin_load 0.0500 [get_ports {cmp_rst}]
set_load -pin_load 0.0500 [get_ports {dout_valid}]
set_load -pin_load 0.0500 [get_ports {eoc}]
set_load -pin_load 0.0500 [get_ports {samp_bot}]
set_load -pin_load 0.0500 [get_ports {samp_top}]
set_load -pin_load 0.0500 [get_ports {dac_n[9]}]
set_load -pin_load 0.0500 [get_ports {dac_n[8]}]
set_load -pin_load 0.0500 [get_ports {dac_n[7]}]
set_load -pin_load 0.0500 [get_ports {dac_n[6]}]
set_load -pin_load 0.0500 [get_ports {dac_n[5]}]
set_load -pin_load 0.0500 [get_ports {dac_n[4]}]
set_load -pin_load 0.0500 [get_ports {dac_n[3]}]
set_load -pin_load 0.0500 [get_ports {dac_n[2]}]
set_load -pin_load 0.0500 [get_ports {dac_n[1]}]
set_load -pin_load 0.0500 [get_ports {dac_n[0]}]
set_load -pin_load 0.0500 [get_ports {dac_p[9]}]
set_load -pin_load 0.0500 [get_ports {dac_p[8]}]
set_load -pin_load 0.0500 [get_ports {dac_p[7]}]
set_load -pin_load 0.0500 [get_ports {dac_p[6]}]
set_load -pin_load 0.0500 [get_ports {dac_p[5]}]
set_load -pin_load 0.0500 [get_ports {dac_p[4]}]
set_load -pin_load 0.0500 [get_ports {dac_p[3]}]
set_load -pin_load 0.0500 [get_ports {dac_p[2]}]
set_load -pin_load 0.0500 [get_ports {dac_p[1]}]
set_load -pin_load 0.0500 [get_ports {dac_p[0]}]
set_load -pin_load 0.0500 [get_ports {dout[9]}]
set_load -pin_load 0.0500 [get_ports {dout[8]}]
set_load -pin_load 0.0500 [get_ports {dout[7]}]
set_load -pin_load 0.0500 [get_ports {dout[6]}]
set_load -pin_load 0.0500 [get_ports {dout[5]}]
set_load -pin_load 0.0500 [get_ports {dout[4]}]
set_load -pin_load 0.0500 [get_ports {dout[3]}]
set_load -pin_load 0.0500 [get_ports {dout[2]}]
set_load -pin_load 0.0500 [get_ports {dout[1]}]
set_load -pin_load 0.0500 [get_ports {dout[0]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__buf_4 -pin {Z} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_out}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__buf_4 -pin {Z} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__buf_4 -pin {Z} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {start}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 2.5000 [current_design]
set_max_fanout 6.0000 [current_design]
