// Auto-generated by LibreLane
module sar_logic_diff(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  input clk,
  input rst_n,
  input start,
  input comp_out,
  output samp_top,
  output samp_bot,
  output cmp_rst,
  output cmp_clk,
  output[9:0] dac_p,
  output[9:0] dac_n,
  output busy,
  output eoc,
  output dout_valid,
  output[9:0] dout
);
endmodule
